Repository jpmoncao/biblify, pull requests merged in 2025-01, with the labels that each got.

#2 feat: README.md realocado
  .github/README.md
  README.md
Labels: documentation

#4 Bug do scroll voltando ao topo ao atualizar a página
  src/components/bible-reader/reader.tsx
  src/main.tsx
  src/pages/books.tsx
  src/pages/home.tsx
  src/pages/settings.tsx
  src/pages/versions.tsx
Labels: bug

#9 feat: Cadastro e Login do Usuário
  api/src/controllers/user.ts
  api/src/routers/user.ts
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ui/form.tsx
  client/src/hooks/use-settings.ts
  client/src/pages/cadaster.tsx
  client/src/pages/home.tsx
  client/src/pages/login.tsx
  client/src/pages/profile.tsx
Labels: new feature
